import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import OIChartAlpha5 from "../components/OIChartAlpha5";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Options Interest Chart</h1>

        <p className={styles.description}>
          KLineCharts v10 alpha5 with OI overlay (CE = green, PE = red)
        </p>

        <div style={{ width: '100%', maxWidth: '1200px', margin: '0 auto' }}>
          <OIChartAlpha5 />
        </div>
      </main>
    </div>
  );
};

export default Home;
